package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u141/9370/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, July 12, 2017 4:37:00 AM PDT
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
     * The CDR Encapsulation encoding.
     * @see CodecFactory
     */
  public static final short value = (short)(0);
}
